version: '3.8'
services:
  h2db:
    image: oscarfonts/h2:1.4.200
    container_name: h2_database
    ports:
      - "9092:9092"
      - "8082:8082" # H2 웹 콘솔
    environment:
      - H2_OPTIONS=-tcpAllowOthers

  redis:
    image: redis:7.0
    container_name: redis_server
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2db:9092/~/datajpa
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - h2db
      - redis