version: '3.8'
services:
  redis:
    image: redis:7.0
    container_name: redis_server
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
#      - "9095:9092"
      - "9095:9095"
#      - "9092:9092"
    environment:
      # 중요: zookeeper 주소 설정
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # kafka 브로커가 호스트에서 접근될 주소
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false  # 보안을 비활성화 (개발 환경)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data    # 데이터 디렉토리 영구화
#      - ./es_data:/usr/share/elasticsearch/data
      - ./es_logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring_boot_app
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#    depends_on:
#      - redis
#      - kafka

  nginx:
#    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: custom-nginx:1.0
    container_name: nginx_server
#    depends_on:
#      - app
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/cache:/var/cache/nginx  # 캐시 디렉토리
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  es_data: