spring:
 redis:
    host: localhost
    port: 6379
    password:   # 비밀번호가 있을 경우 추가
    database: 0
 datasource:
   url: jdbc:h2:tcp://localhost/~/datajpa
   username: sa
   password:
   driver-class-name: org.h2.Driver
 jpa:
   hibernate:
     ddl-auto: create
   properties:
     hibernate:
# show_sql: true
       format_sql: true
   data:
     web:
       pageable:
         default-page-size: 10
         max-page-size: 2000
         one-indexed-parameters: true
logging.level:
 org.hibernate.SQL: debug
# org.hibernate.type: trace
#trace옵션은 파라미터 바인딩된 쿼리까지 볼 수 있다.

jwt:
  secret: your-secret-key  # JWT 서명에 사용할 비밀 키
  expiration: 3600000      # JWT 만료 시간 (밀리초 단위, 예: 1시간)


